language: python

python:
  - "3.5"
  - "3.6"

install:
  - pip install codecov
  - pip install -r requirements-dev.txt

script:
  - python -m pytest --cov=./ --cov-report term-missing --cov-config=.coveragerc ./tests/

after_success:
  - codecov
