language: python

python:
  - "3.5"
  - "3.6"

install:
  - pip install codecov
  - pip install -r requirements-dev.txt

script:
  - python -m pytest --cov=./ --cov-report term-missing --cov-config=.coveragerc ./tests/tests_1_unit/
  - codecov -F unittests
  - python -m pytest --cov=./ --cov-report term-missing --cov-config=.coveragerc ./tests/tests_2_integrat/
  - codecov -F integration

after_success:
  - pycodestyle --statistics LibreCisco
  - codecov
